#!/usr/bin/env python

import signal,time

print "setting TERM handler"
signal.signal(signal.SIGTERM, signal.SIG_IGN)
print "TERM handler set"

print "and now I sleep"
time.sleep(10)
print "ok, now I'm done sleeping, thanks for the rest"

